version: 0.2

phases:
    pre_build:
        commands:
        - echo Restore started on `date`
        #- dotnet restore cicd_WebApi1.csproj
    build:
        commands:
        - echo Build started on `date`
        - dotnet build ./build_output cicd_WebApi1.csproj
        - dotnet publish -c release -o ./build_output cicd_WebApi1.csproj
artifacts:
    files:
    - '**/*'
