version: 0.2

phases:
    pre_build:
        commands:
        - echo Restore started on `date`
        - dotnet restore cicd_WebApi1.csproj
    build:
        commands:
        - echo Build started on `date`
        - dotnet publish -c release -o ./build_output cicd_WebApi1.csproj
artifacts:
    files:
    - s3://codepipeline-eu-west-1-853934031582/cicd_webapp_test_nev/SourceArti/Lza631S.zip